#!/usr/bin/env python

Import("env")

env_game = env.Clone()

module_obj = []
if env.debug_features:
    # Need imgui
    env_game.Prepend(CPPPATH=["#modules/imgui/thirdparty/imgui"])
env_game.Prepend(CPPPATH=["#modules/jolt/src"])
env_game.Prepend(CPPPATH=["#modules/jolt/thirdparty/jolt"])
env_game.Prepend(CPPPATH="#modules/jolt/thirdparty/mimalloc/include")

env_game.Prepend(CPPDEFINES=["USINGZ"])
env_game.Prepend(CPPPATH=["#modules/game/thirdparty/clipper2"])

sources = [
    Glob("*.cpp"),
    Glob("animation_system/*.cpp"),
    Glob("fabrik/*.cpp"),
    Glob("npc_brains/*.cpp"),
]

thirdparty_obj = []
thirdparty_sources = [
    Glob("thirdparty/clipper_3d/*.cpp"),
    Glob("thirdparty/goap/*.c"),
]

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env_thirdparty.modules_sources += thirdparty_obj

if ARGUMENTS.get("game_shared", "no") == "yes":
    # Shared lib compilation
    env_game.Append(CCFLAGS=["-fPIC"])
    env_game["LIBS"] = []
    shared_lib = env_game.SharedLibrary(target="#bin/game", source=sources)
    shared_lib_shim = shared_lib[0].name.rsplit(".", 1)[0]
    env.Append(LIBPATH=["#bin"])
    env.Append(LIBS=["libgame.linuxbsd.editor.dev.x86_64"])
else:
    env_game.add_source_files(module_obj, sources)
    env.modules_sources += module_obj

env_game.Depends(module_obj, thirdparty_obj)

SConscript("resources/SCsub")
