#!/usr/bin/env python

Import("env")
Import("env_modules")

env_imgui = env_modules.Clone()

module_obj = []
thirdparty_obj = []
thirdparty_dir = "#modules/imgui/thirdparty/imgui/"

thirdparty_sources = [
    "imgui_demo.cpp",
    "imgui_draw.cpp",
    "imgui_tables.cpp",
    "imgui_widgets.cpp",
    "imgui.cpp",
    "imnodes.cpp",
    "ImGuizmo.cpp",
    "imgui_neo_internal.cpp",
    "imgui_neo_sequencer.cpp",
    "misc/freetype/imgui_freetype.cpp",
    "implot.cpp",
    "implot_items.cpp",
]

thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_imgui.Prepend(CPPPATH=[thirdparty_dir])
freetype_enabled = "freetype" in env.module_list

env_thirdparty = env_imgui.Clone()
if env["builtin_freetype"] and freetype_enabled:
    env_thirdparty.Prepend(CPPPATH=["#thirdparty/freetype/include"])

env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(module_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

env_imgui.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)

SConscript("thirdparty/fonts/SCsub")
