#!/usr/bin/env python

Import("env")
Import("env_modules")

env_imgui = env_modules.Clone()

module_obj = []
thirdparty_obj = []
thirdparty_dir = "#modules/imgui/thirdparty/imgui/"

thirdparty_sources = ["imgui_demo.cpp", "imgui_draw.cpp", "imgui_tables.cpp", "imgui_widgets.cpp", "imgui.cpp"]

thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_imgui.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_imgui.Clone()
env_thirdparty.disable_warnings()
env_imgui.add_source_files(thirdparty_obj, "*.cpp")
env.modules_sources += thirdparty_obj

env_imgui.add_source_files(module_obj, thirdparty_sources)

env.modules_sources += module_obj
